# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingNode',
            fields=[
                ('id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('x', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('y', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('xa', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('ya', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('xb', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('yb', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('xc', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('yc', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('xd', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('yd', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=10)),
                ('cuttingXList', models.CharField(blank=True, default='', max_length=40)),
                ('cuttingYList', models.CharField(blank=True, default='', max_length=40)),
                ('transformMat', models.CharField(blank=True, default='', max_length=100)),
                ('toploMat', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='RecombinationNode',
            fields=[
                ('id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('toploMat', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
