# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_recombinationnode_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recombinationnode',
            name='position',
        ),
    ]
