# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_recombinationnode_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='recombinationnode',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recombinationnode',
            name='isTimedRecording',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recombinationnode',
            name='startTime',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
