# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20170925_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recombinationnode',
            name='position',
        ),
        migrations.RemoveField(
            model_name='recombinationnode',
            name='toploMat',
        ),
    ]
