# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20170925_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerainfo',
            name='cuttingXList',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='cuttingYList',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='toploMat',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='transformMat',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='xa',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='xb',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='xc',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='xd',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='ya',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='yb',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='yc',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='yd',
        ),
    ]
