# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_auto_20170926_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recombinationnode',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
