# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_auto_20170928_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerainfo',
            name='coordinate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
