# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_camerainfo_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerainfo',
            name='x',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='y',
        ),
        migrations.AlterField(
            model_name='camerainfo',
            name='ip',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
